### ISSUE TITLE
0.33.0 regression with vue 2 on template type checking

### ISSUE THREAD

**Issue by J3m5** [johnsoncodehk/volar#1035]
Hello

After updating to 0.33.0, the `Cannot find name '...' .ts(2304)` errors are displayed on all variables returned in the setup function.

I'm using `defineComponent` from `@vue/runtime-dom` on exported JavaScript components.
The errors are not there with the previous version 0.32.1.

Tested with "Take over mode" enabled and disabled

"@vue/runtime-dom": "3.2.31",
 "vue": "2.6.14",
"@vue/composition-api": "1.4.9",

Vscode 1.65.2

Thank you for your work

**Comment by johnsoncodehk** [comment]
I can't reproduce this problem, could you provide repro case?

**Comment by johnsoncodehk** [comment]
I suspect it's relate to this commit: https://github.com/johnsoncodehk/volar/commit/8cb50ccf4660f1a27364fc898ac78149c99442fd

Could you try does this version fixed the problem?
[volar-0.33.1-alpha.1.vsix.zip](https://github.com/johnsoncodehk/volar/files/8240008/volar-0.33.1-alpha.1.vsix.zip)

**Comment by J3m5** [comment]
The problem is still there with the version you provided.
Do you know if there is a simple repo somewhere with vue 2, javascript and composition api?

**Comment by johnsoncodehk** [comment]
This is close: https://github.com/johnsoncodehk/volar-starter/tree/vue2

**Comment by J3m5** [comment]
I'll try that and report back to you
I don't know if it's relevant but I'm using @vue/cli-service v4.5.15

**Comment by johnsoncodehk** [comment]
I'll be releasing a new version soon, and if you can provide a repro case I'll fix it before release. :)

**Comment by J3m5** [comment]
I've create a fresh project with vue cli and I encounter the same problem.
I'll provide a link to it quickly.

**Comment by J3m5** [comment]
The repo is there: https://github.com/J3m5/volar-repro-issue-1035
I tried with the original 0.33.0 and the one you provided.

**Comment by zardoy** [comment]
> This is close: https://github.com/johnsoncodehk/volar-starter/tree/vue2

I don't know wether its related but you can also just add `"allowJs": true` into `compilerOptions` of tsconfig and remove `lang=ts` in `src/components/HelloWorld.vue`. Everything worked as expected in `v0.30.3`

**Comment by J3m5** [comment]
> I don't know wether its related but you can also just add `"allowJs": true` into `compilerOptions` of tsconfig and remove `lang=ts` in `src/components/HelloWorld.vue`. Everything worked as expected in `v0.30.3`

My project is using vue-cli with webpack, not vite, so I prefer to stay as close as possible to my setup.

**Comment by johnsoncodehk** [comment]
Please update to 0.33.1 for fix, thanks for the report!

**Comment by J3m5** [comment]
Just tested it and everything is fine.
Thank you for the quick fix!
And as a side effect, it seems that it's not necessary to use defineComponent from @vue/runtime-dom anymore, the one from @vue/composition-api is working fine.
