### ISSUE TITLE
vue-tsc&&typescript&&volar version relationship between them？

### ISSUE THREAD

**Issue by qiaozhu** [johnsoncodehk/volar#285]
what version should i use？
I saw this description in vue-tsc before,But now no more。
![image](https://user-images.githubusercontent.com/25722049/124056907-2a351b00-da59-11eb-9ff4-d9710e3042e3.png)

now i use：
"vue-tsc": "0.2.0"
"typescript": "4.3.4"
volar: 0.25.24

volar type-check is normal
but vue-tsc abnormal：error TS2345
![image](https://user-images.githubusercontent.com/25722049/124057267-b9423300-da59-11eb-80d3-4f4cc1ed58bf.png)

**Comment by johnsoncodehk** [comment]
It seem 0.25.23 problem, and should be fix in 0.25.24: https://github.com/johnsoncodehk/volar/issues/284

Please provide a reproduce if you are using vue-tsc with volar 0.25.24.

Currently vue-tsc do not binding to volar version one by one, vue-tsc@0.2.0 has rely volar@^0.25.22, it mean vue-tsc working with volar@0.25.22~0.25.24 for now.

typescript is peer dependencies in vue-tsc, you need to additionally install a specific version typescript module.

**Comment by qiaozhu** [comment]
Thank you, I reinstalled vue-tsc, dependencies "vscode-vue-languageservice" has been updated to 0.25.24, it's ok;
