### ISSUE TITLE
vue-router 4.2.0 breaks vue-tsc

### ISSUE THREAD

**Issue by jfrs** [johnsoncodehk/volar#3178]
I have project with `vue` 3.3.1, `vue-router` 4.1.6, `vuetify` 3.2.4 and `vue-tsc` 1.6.4 (same with 1.7.1).

When I upgrade `vue-router` to 4.2.0, all the `vuetify` components errors with `Property 'VBtn' does not exist on type 'Pick<IntrinsicElements, "div"> & Pick<{ $: ComponentInternalInstance; $data: {}; $props: { key?: string | number | symbol | undefined; ... 18 more ...; "onUpdate:sessionClip"?: ((sessionClip: SessionClipRequest | null) => any) | undefined; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source...'.`

I don't think it's a `vuetify` issue, but I'm not sure how to check what's happening here.

**Comment by kingyue737** [comment]
Reproduction: https://stackblitz.com/edit/vitejs-vite-iefwye

`vue-router` v4.2.0 augments `ComponentCustomOptions` via declaring `vue` while I (or other libraries) augment this interface with `@vue/runtime-core`. Then this error happens.
