### ISSUE TITLE
Failed to load config

### ISSUE THREAD

**Issue by CheIIau** [johnsoncodehk/volar#1737]
I Tried this plugin on two different computers, on two different projects and always got the same error:

failed to load config from D:\User\vue\test\node_modules\.vite\volar-vite.config.ts
error when starting dev server:
Error: Cannot find module 'D:User♂ue♂est♂ite.config'
...

Tbh, i don't know why it is complaining on that it cannot find vite.config, because it obviously exist
Maybe i'm doing something wrong

**Comment by johnsoncodehk** [comment]
It may fixed by https://github.com/johnsoncodehk/volar/commit/dd9b3612f240f04792aaa1aba4080e391cbab675, please let me know if still not working on 0.40.2.

**Comment by CheIIau** [comment]
Now here is new error message. Previously compiler wasn't able to find srccomponentsHelloWorld.vue, so it seems like it's just throw away slashes.
![image](https://user-images.githubusercontent.com/58114735/187089110-0021036c-4516-4600-a1b7-22c4df72ed1b.png)

**Comment by CheIIau** [comment]
Now it's working. Thank you, it's great, i love it :+1:
