### ISSUE TITLE
False positive TS1323 error about static imports in <script setup lang="ts">

### ISSUE THREAD

**Issue by micgro42** [johnsoncodehk/volar#1263]
When in tsconfig.json the "module" compiler option is set to `es2015`, then `vue-tsc` produces an error for _static_ imports inside `<script setup lang="ts">`

For example for this code straight from the vite scaffold:

```html
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import HelloWorld from './components/HelloWorld.vue'
</script>
```

This is the error message that is produced:

```
src/App.vue:1:1 - error TS1323: Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'es2022', 'esnext', 'commonjs', 'amd', 'system', 'umd', 'node12', or 'nodenext'.
```
As you can see, there is no dynamic import in App.vue, only a static one.

I create a minimal failing example repository for this, reproducing the error on `npm run build`: https://github.com/micgro42/Minimal-Failing-Example_volar-dynamic-import

It is the repository produced by `npm create vite@latest` and the `tsconfig.json` modified as stated above.

As far as I can tell, this started with vue-tsc 0.34.x. That is, it was working fine with 0.33.9 and broke when we tried to upgrade to 0.34.11.

Please let me know if you need any further information.

**Comment by micgro42** [comment]
Thank you!
