### ISSUE TITLE
Request textDocument/foldingRange failed: host.fileExists is not a function

### ISSUE THREAD

**Issue by Sfinx** [johnsoncodehk/volar#1870]
after upgrading from 1.71.0 to 1.71.1 this message appears every time I'm clicking on tab with saved folding range:

```
[Error - 10:18:35 AM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: host.fileExists is not a function
  Code: -32603 
```

trace:

```
 ERR Request textDocument/foldingRange failed with message: host.fileExists is not a function: Error: Request textDocument/foldingRange failed with message: host.fileExists is not a function
	at handleResponse (/home/xxx/.vscode-oss/extensions/johnsoncodehk.volar-0.30.1/node_modules/vscode-jsonrpc/lib/common/connection.js:498:48)
	at processMessageQueue (/home/xxx/.vscode-oss/extensions/johnsoncodehk.volar-0.30.1/node_modules/vscode-jsonrpc/lib/common/connection.js:296:17)
	at Immediate.<anonymous> (/home/xxx/.vscode-oss/extensions/johnsoncodehk.volar-0.30.1/node_modules/vscode-jsonrpc/lib/common/connection.js:280:13)
	at process.processImmediate (node:internal/timers:466:21)
```

**Comment by Sfinx** [comment]
Upgrading volar to 0.40.13 fixes this issue
