### PR TITLE
perf(language-core): rewrite a subset of template node transforms

### LINKED ISSUE #4539: key is not type-checked on `template`
### Vue - Official extension or vue-tsc version

2.0.26

### VSCode version

1.92.0-insider

### Vue version

3.4.31

### TypeScript version

5.5.3

### System Info

_No response_

### Steps to reproduce

1. `git clone git@github.com:brc-dd/volar-template-key-bug.git`
2. `pnpm i`
3. `pnpm vue-tsc --noEmit`

### What is expected?

Error on both line 4 and line 5 of `Foo.vue`

### What is actually happening?

Error is only on line 5. There should be an error saying `Type '{}' is not assignable to type 'PropertyKey | undefined'.` for `:key` prop of `<template>` too.

### Link to minimal reproduction

https://github.com/brc-dd/volar-template-key-bug

### Any additional comments?

_No response_

### LINKED ISSUE #5492: v-else-if and v-slot co-usage triggers false ts-plugin(6133) "unused" warning/error
### Vue - Official extension or vue-tsc version

3.0.1

### VSCode version

1.102.0

### Vue version

3.5.17

### TypeScript version

5.8.3

### System Info

```shell

```

### package.json dependencies

```json

```

### Steps to reproduce

1. Create a new Vue 3.5+ project using `<script setup lang="ts"`.
2. Install and use the **Vue - Official** extension in VS Code.
3. Add an imported function in `<script setup lang="ts"` that will **only be used inside** `v-else-if` block in the template.
4. Use the function in the template like this:

``` vue 3.5
<template>
  <div>
    <div v-if="func1()"></div>
    <div v-else-if="func2()></div>
    <div v-else></ div>
  </div>
</template>
<script setup lang="ts">
import { func1, func2 } from "somewhere" // `func2` is declared but its value is never read. ts-plugin(6133)
</script>
```

### What is expected?

The imported function `func2` should not trigger ts-plugin(6133) warning/error if it is used anywhere in the template, even inside a `v-else-if`.

### What is actually happening?

The imported function is marked as **unused** (ts-plugin(6133) warning/error) when used **only inside a** `v-else-if` expression, despite being referenced in the template.

### Link to minimal reproduction

_No response_

### Any additional comments?

_No response_

### LINKED ISSUE #5899: Getting error TS1005 after upgrading from v3.1.5
### Vue - Official extension or vue-tsc version

3.2.1

### VSCode version

1.105.1

### Vue version

3.5.26

### TypeScript version

5.9.3

### System Info

```shell
System:
  OS: Windows 11 10.0.26100
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Memory: 2.57 GB / 15.69 GB
Binaries:
  Node: 22.17.1 - C:\Program Files\nodejs\node.EXE
  npm: 10.9.2 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Chrome: 143.0.7499.146
  Edge: Chromium (140.0.3485.54)
  Firefox: 146.0 - C:\Program Files\Mozilla Firefox\firefox.exe
  Internet Explorer: 11.0.26100.1882
```

### package.json dependencies

```json
{
  "dependencies": {
    "awesome-phonenumber": "^7.2.0",
    "mitt": "^3.0.1",
    "quill": "^2.0.3",
    "vue-quilly": "^1.1.5"
  },
  "devDependencies": {
    "@eslint/compat": "^2.0.0",
    "@testing-library/jest-dom": "^6.9.1",
    "@testing-library/user-event": "^14.6.1",
    "@testing-library/vue": "^8.1.0",
    "@types/google.maps": "^3.58.1",
    "@types/jsdom": "^27.0.0",
    "@types/node": "^22.18.13",
    "@vitejs/plugin-vue": "^6.0.3",
    "@vue/test-utils": "^2.4.6",
    "eslint": "^9.39.2",
    "eslint-import-resolver-typescript": "^4.4.4",
    "eslint-plugin-import-x": "^4.16.1",
    "jsdom": "^27.3.0",
    "npm-run-all2": "^8.0.4",
    "prettier": "^3.7.4",
    "pug": "^3.0.3",
    "rimraf": "^6.0.1",
    "sass": "~1.97.1",
    "stylelint": "^16.26.1",
    "typescript": "^5.9.3",
    "vitest": "^4.0.16",
    "vue-tsc": "^3.2.1"
  },
  "peerDependencies": {
    "vue": "^3.5.26",
    "vue-i18n": "^11.2.7",
    "vue-router": "^4.6.4"
  }
}
```

### Steps to reproduce

I've just executed the same `npm run type-check` command I always run (`tsc --noEmit`)

### What is expected?

A successful execution

### What is actually happening?

error TS1005: ')' expected

### Link to minimal reproduction

_No response_

### Any additional comments?

It worked fine until v3.1.6. After upgrading to v3.1.6, the error appeared. I had to downgrade.

I use pug for templates and ts for the script. Also using `@vue/language-plugin-pug` with the same version as `vue-tsc`

### LINKED ISSUE #5914: Failing to parse pug function call inside a conditional named template slot (regression since 3.1.6)
### Vue - Official extension or vue-tsc version

3.2.1

### VSCode version

- (repeatable in command line, no need to have VSCode)

### Vue version

3.5.26

### TypeScript version

5.9.3

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### package.json dependencies

```json
"dependencies": {
    "vue": "^3.5.26",
    "vue-router": "^4.6.4"
  },
  "devDependencies": {
    "@vue/language-plugin-pug": "^3.2.1",
    "nuxt": "^3.20.2",
    "pug": "^3.0.3",
    "typescript": "^5.9.3",
    "vue-tsc": "^3.2.1"
  }
```

### Steps to reproduce

```vue
<script setup lang="ts">
function getNumber() {
  return 123;
}
</script>

<template lang="pug">
test-view
  template(v-if="true" #help)
    | {{ getNumber() }}
</template>
```

From what I've tested, all parts are required: it should be a non-default slot with v-if, and a function call.

In the minimal reproduction at Stackblitz (see link below), this code is inside `app.vue`. To repeat the bug, simply run:

```sh
pnpm nuxt typecheck
```

### What is expected?

No error during type check — the code is valid.

### What is actually happening?

```
❯ pnpm nuxt typecheck

 ERROR  (node:30) ExperimentalWarning: WASI is an experimental feature and might change at any time          4:11:38 PM
(Use node --trace-warnings ... to show where the warning was created)

app.vue:10:22 - error TS1005: ')' expected.

10     | {{ getNumber() }}
                        ~


Found 1 error in app.vue:10
```

### Link to minimal reproduction

https://stackblitz.com/edit/nuxt-starter-yl6fbd5x

### Any additional comments?

I bisected this to be a regression introduced in vue-tsc 3.1.6. The code is handled fine in 3.1.5 and earlier.

### PR DESCRIPTION
**Pull request by KazariEX**
fix #4539, fix #5492, fix #5899, fix vuejs/core#12258, close #5765

This change simplifies the transforms of the template AST, in particular by removing all `codegenNode` that existed only for runtime codegen purpose. This also results in an AST shape that is more favorable for language tools integration.

### CODE REVIEW

File: test-workspace/tsc/passedFixtures/vue3/#5492/main.vue [hunk 1]
```diff
@@ -1,19 +1,15 @@
...
+	<template v-else-if="false" :bar />
 	<Comp>
-		<template #default v-if="cond1">1</template>
-		<template #default v-else-if="cond2">2</template>
-
-		<div v-if="cond1 === true"></div>
-		<div v-else-if="cond1.length"></div>
-
-		<template #default v-if="cond1 === true">1</template>
-		<template #default v-else-if="cond1.length">2</template>
```
Comment (serkodev) [inline test-workspace/tsc/passedFixtures/vue3/#5492/main.vue]: the fixture of `v-else-if="cond1.length"` is for checking type narrowing
