### ISSUE TITLE
'... is declared but its value is never read' in vue-tsc 0.40.0 and onwards

### ISSUE THREAD

**Issue by samardzicneo** [johnsoncodehk/volar#1748]
Hello

Since updating to 0.40.0 (and later 0.40.1), we are unable to use vue-tsc on our project. On that version, we get errors like these on pretty much all of our Vue SFCs:
```
...
src/[...].vue - error TS6133: '...' is declared but its value is never read.
...
```
We are using Vue 3 and SFCs with setup scripts all throughout our application.

Reading other issues that reported similar issues, it looks like they were either using Vue 2 or had their issue fixed by editing their `tsconfig.json`. However, we use Vue 3 and our `tsconfig.json` includes these lines:
```json
{
  "compilerOptions": {
    ...
    "jsx": "preserve",
    ...
  },
  "vueCompilerOptions": {
    "experimentalDisableTemplateSupport": true
  }
}
```

Our project was ported from using `vue-cli` and we didn't consider type-checking in templates at the time, which is why we need `experimentalDisableTemplateSupport` enabled. Disabling it gets rid of these errors, but introduces hundreds of other ones. Also, the IDE (WebStorm) some of us use didn't support Typescript syntax inside templates at the time.

**Comment by johnsoncodehk** [comment]
Duplicate of #1729

**Comment by sschneider-ihre-pvs** [comment]
Doesn't seem to fix it for me. I have that problem for components and variables from setup that are used in the template.

**Comment by johnsoncodehk** [comment]
@sschneider-ihre-pvs Please open a new issue and provide minimal reproduction if you have the problem in the latest version.
