### ISSUE TITLE
Empty attribute infer doesn't work with "boolean | undefined" since 0.25.25

### ISSUE THREAD

**Issue by davidmatter** [johnsoncodehk/volar#288]
The `active` attribute should be inferred correctly in the following code:

```html
<Card>
    <template #content>
        <Steps>
            <StepsItem :number="1" title="Test" active></StepsItem>
            <StepsItem :number="2" title="Test"></StepsItem>
            <StepsItem :number="3" title="Test"></StepsItem>
        </Steps>
    </template>
</Card>
```

The component props definition:

```typescript
export default defineComponent({
  name: 'StepsItem',
  props: {
    ...
    active: {
      type: Boolean,
      required: false,
    },
    ...
  },
})
```

Since **v0.25.25**, the following error is thrown:

```
../common/src/Styleguide.vue:195:47 - error TS2322: Type 'unknown' is not assignable to type 'boolean | undefined'.
  Type 'unknown' is not assignable to type 'true'.

195           <StepsItem :number="1" title="Test" active></StepsItem>
```

**Comment by johnsoncodehk** [comment]
Fixed in https://github.com/johnsoncodehk/volar/commit/f1288eb92db2e13f3b3139e1c38733835a66579e, thanks for the report!

**Comment by davidmatter** [comment]
Thanks for the fix!
