### ISSUE TITLE
Commonjs modules cannot pass the vue-tsc check after upgrading version from 3.1.6 to 3.1.7

### ISSUE THREAD

**Issue by melon** [johnsoncodehk/volar#5821]
### Vue - Official extension or vue-tsc version

3.1.7

### VSCode version

Whatever

### Vue version

Whatever

### TypeScript version

Whatever

### System Info

```shell

```

### package.json dependencies

```json

```

### Steps to reproduce

The following simple snippet can be used to reproduce the bug.

```vue
<script lang="ts" setup>
import dayjs from 'dayjs';
</script>

<template>
  {{ dayjs().format('YYYY-MM-DD HH:mm:ss') }}
</template>
```

When executing `npx vue-tsc --noEmit`, the following error occurs.

```bash
src/Test.vue:6:6 - error TS2339: Property 'dayjs' does not exist on type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}, {}, string, {}, {}, {}, string, ComponentProvideOptions>, ... 4 more ..., any>'.

6   {{ dayjs().format('YYYY-MM-DD HH:mm:ss') }}
```

### What is expected?

The simple snippet should pass the typescript check.

### What is actually happening?

**The version 3.1.6 works well, whereas the version 3.1.7 doesn't.**

I guess the issue is related to the module system (commonjs vs es6) the imported package used.

day.js uses the old commonjs module system, which might be the cause of the issue.

```
/// <reference path="./locale/index.d.ts" />

export = dayjs;

declare function dayjs (date?: dayjs.ConfigType): dayjs.Dayjs

declare function dayjs (date?: dayjs.ConfigType, format?: dayjs.OptionType, strict?: boolean): dayjs.Dayjs

declare function dayjs (date?: dayjs.ConfigType, format?: dayjs.OptionType, locale?: string, strict?: boolean): dayjs.Dayjs

declare namespace dayjs
...
```

**Comment by liuheo** [comment]
😂 
``` vue
<script setup lang="ts">
import dayjs from "dayjs";
const _dayjs = dayjs;
</script>

<template>
  <div>{{ _dayjs().format('YYYY-MM-DD HH:mm:ss') }}</div>
</template>

**Comment by ntnyq** [comment]
Not related to module system.

I got the following error with code bellow

`Property 'zhCN' does not exist on type '{ ElConfigProvider: SFCWithInstall<DefineComponent<{ readonly emptyValues: ArrayConstructor; readonly valueOnClear: EpPropFinalized<(new (...args: any[]) => string | number | boolean | Function) | (() => string | number | boolean | Function | null) | ((new (...args: any[]) => string | ... 2 more ... | Function) | ((...'.`

```vue
<script setup lang="ts">
  import { ElConfigProvider } from 'element-plus'
  import zhCN from 'element-plus/es/locale/lang/zh-cn'
</script>

<template>
  <ElConfigProvider :locale="zhCN" />
</template>
```

`zhCn` is imported from an esm file.

Reproduction repo: https://github.com/ntnyq-dev/repro-vue-tsc-issue

**Comment by ntnyq** [comment]
Duplicated with https://github.com/vuejs/language-tools/issues/5819
