### ISSUE TITLE
Build fails after upgrade vue-tsc to 0.30.4

### ISSUE THREAD

**Issue by NoahStahl** [johnsoncodehk/volar#865]
After upgrading `vue-tsc` package from 0.30.2 to 0.30.4, vite build now fails with below output. Reverting to 0.30.2 gets to working build again. Happy to provide other info as needed. Not sure on the apparent mangling of output with missing first characters.

```
> vue-tsc --noEmit && vite build

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:CodeSkyPlugSkyPlug.WebApp
ode_modules.pnpm
ue-tsc@0.30.4_typescript@4.5.4
ode_modules
ue-tscoutproxy.js'
Require stack:
- C:\Code\SkyPlug\SkyPlug.WebApp\node_modules\.pnpm\typescript@4.5.4\node_modules\typescript\lib\tsc.js
- C:\Code\SkyPlug\SkyPlug.WebApp\node_modules\.pnpm\vue-tsc@0.30.4_typescript@4.5.4\node_modules\vue-tsc\bin\vue-tsc.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.createProgram (C:\Code\SkyPlug\SkyPlug.WebApp\node_modules\.pnpm\typescript@4.5.4\node_modules\typescript\lib\tsc.js:93628:118)
    at performCompilation (C:\Code\SkyPlug\SkyPlug.WebApp\node_modules\.pnpm\typescript@4.5.4\node_modules\typescript\lib\tsc.js:101963:26)
    at executeCommandLineWorker (C:\Code\SkyPlug\SkyPlug.WebApp\node_modules\.pnpm\typescript@4.5.4\node_modules\typescript\lib\tsc.js:101848:17)
    at Object.executeCommandLine (C:\Code\SkyPlug\SkyPlug.WebApp\node_modules\.pnpm\typescript@4.5.4\node_modules\typescript\lib\tsc.js:101893:20)
    at Object.<anonymous> (C:\Code\SkyPlug\SkyPlug.WebApp\node_modules\.pnpm\typescript@4.5.4\node_modules\typescript\lib\tsc.js:102187:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Code\\SkyPlug\\SkyPlug.WebApp\\node_modules\\.pnpm\\typescript@4.5.4\\node_modules\\typescript\\lib\\tsc.js',
    'C:\\Code\\SkyPlug\\SkyPlug.WebApp\\node_modules\\.pnpm\\vue-tsc@0.30.4_typescript@4.5.4\\node_modules\\vue-tsc\\bin\\vue-tsc.js'
  ]
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by johnsoncodehk** [comment]
Thanks for your report! Could you try replace below code in node_modules/vue-tsc/bin/vue-tsc.js and run again?

```diff
#!/usr/bin/env node
const fs = require('fs');

const readFileSync = fs.readFileSync;
const tscPath = require.resolve('typescript/lib/tsc');
const proxyPath = require.resolve('../out/proxy');

fs.readFileSync = (...args) => {
    if (args[0] === tscPath) {
        let tsc = readFileSync(...args);
        tsc = tsc.replace(
            `function createIncrementalProgram(_a) {`,
            `function createIncrementalProgram(_a) { console.error('incremental mode is not yet support'); throw 'incremental mode is not yet support';`,
        );
        tsc = tsc.replace(
            `function createWatchProgram(host) {`,
            `function createWatchProgram(host) { console.error('watch mode is not yet support'); throw 'watch mode is not yet support';`,
        );
        tsc = tsc.replace(
            `function createProgram(rootNamesOrOptions, _options, _host, _oldProgram, _configFileParsingDiagnostics) {`,
-            `function createProgram(rootNamesOrOptions, _options, _host, _oldProgram, _configFileParsingDiagnostics) { return require('${proxyPath}').createProgramProxy(...arguments);`,
+            `function createProgram(rootNamesOrOptions, _options, _host, _oldProgram, _configFileParsingDiagnostics) { return require(${JSON.stringify(proxyPath)}).createProgramProxy(...arguments);`,
        );
        return tsc;
    }
    return readFileSync(...args);
};

require(tscPath);
```

**Comment by crutchcorn** [comment]
@johnsoncodehk I am experiencing this issue as well. 

With your supplied fix, sure enough I'm now getting proper TS type errors as-expected instead of the incorrect message

**Comment by NoahStahl** [comment]
Thanks for the quick reply! That change does appear to fix, and the build once again succeeds.

**Comment by johnsoncodehk** [comment]
@crutchcorn @NoahStahl thanks to confirm this!
