### ISSUE TITLE
[question] How to type multiple emits, is supported by Volar ?

### ISSUE THREAD

**Issue by germsb** [johnsoncodehk/volar#124]
```typescript
const emit = defineEmit<
    (e: 'date',id: number) => void
    | ((e: 'day', id: string) => void)
>();
```
`date` is autocompleted both in and out the component
`day` throw `Argument of type '"day"' is not assignable to parameter of type '"date"'`

[repro](https://github.com/germsb/volarTest)  

![Imgur](https://i.imgur.com/867SI2V.jpg)

edit: newbie in ts :)

**Comment by johnsoncodehk** [comment]
Hi @germsb, try this:

```ts
const emit = defineEmit<{
    (e: 'date',id: number): void
    (e: 'day', id: string): void
}>();
```

**Comment by germsb** [comment]
Thank you !

**Comment by germsb** [comment]
oups, finally I get an error from Vite :  
```shell-script
[vite] Internal server error: [@vue/compiler-sfc] type argument passed to defineEmit() must be a function type or a union of function types.

/home/germs/dev/rentool-monorepo/packages/frontend/components/ui/src/pendingComponents/CDatePicker.vue
130|      },
131|  });
132|  const emit = defineEmit<{
   |                          ^
133|      (e: 'date', id: number): void;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
134|      (e: 'day', id: string): void;
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
135|  }>();
   |  ^
```

**Comment by johnsoncodehk** [comment]
This is upstream issue, you could switch to options api for now:

```ts
const emit = defineEmit({
    date: (id: number) => true,
    day: (id: string) => true,
});
```

**Comment by germsb** [comment]
As much for me, work fine after update vue and compiler to 3.0.11. 
On the other hand, when build, `vue-tsc` is not happy:  
```shell-script
> vue-tsc --noEmit && vite build

src/App.vue:3:22 - error TS7006: Parameter 'v' implicitly has an 'any' type.

3   <HelloWorld @date="v => {}" @day="v => {}" msg="Hello Vue 3 + TypeScript + Vite" />
                       ~

src/App.vue:3:37 - error TS7006: Parameter 'v' implicitly has an 'any' type.

3   <HelloWorld @date="v => {}" @day="v => {}" msg="Hello Vue 3 + TypeScript + Vite" />
                                      ~


Found 2 errors.
```

**Comment by johnsoncodehk** [comment]
Are you using `vue-tsc` latest version 0.0.20?

**Comment by germsb** [comment]
`"vue-tsc": "latest"`  [repo forked from volar-starter](https://github.com/germsb/volarTest)

**Comment by johnsoncodehk** [comment]
You need to check the version in `node_modules`, because `vue-tsc` often update. 😅 (for example, now is 0.0.21)

**Comment by germsb** [comment]
it was en 0.0.20,  now in 0.0.21 everything seems ok !!  :D
