### ISSUE TITLE
Bug: Cannot find name 'vShow'

### ISSUE THREAD

**Issue by raymer** [johnsoncodehk/volar#1036]
After upgrade to 0.33.0 I get an error when using the v-show directive:

![image](https://user-images.githubusercontent.com/490221/158067670-bd1e7e6e-9d72-47e4-ac0d-9f6c3149d3c1.png)

This didn't occur prior to this update.

**Comment by OfekA-IAI** [comment]
Getting the same behavior

**Comment by johnsoncodehk** [comment]
Will release new version soon, thanks for the report!
